### ISSUE TITLE
Dataset and code for pretraining word embeddings

### ISSUE THREAD

**Issue by qibinc** [sola-st/IdBench#1]
Dear authors,

Thanks for the fantastic work! I really enjoy reading it and wish to follow up the experiments.

Is it possible for you to release the your preprocessed 50k Javascript dataset and your code for training the methods in the paper, so that we can run the whole experiments and learn more from this work? I would really appreciate this.

Thanks in advance!

**Comment by michaelpradel** [comment]
Thanks for your interest. We're looking into it and will get back to you here.

**Comment by michaelpradel** [comment]
The code and instructions for training the embeddings yourself are now available in [this newly added section of the README](https://github.com/sola-st/IdBench/#training-the-embedding-models-yourself). Hope that helps!
