### ISSUE TITLE
Request for Releasing Interesting Subsets of IdBench-small

### ISSUE THREAD

**Issue by qibinc** [sola-st/IdBench#3]
Dear authors,

In the paper, Section III. Results C. RQ 3 2) *Interesting Subsets of All Identifier Pairs*, there are five subsets (Abbreviations, Opposites, Synonyms, Added subtoken, Tricky tokenization) studied to show the methods' performance on these subsets. Is it possible to release the exact pairs included in each subset?

Thanks!

**Comment by michaelpradel** [comment]
Thanks for your question. Sure! We just shared the subsets in this commit: 66e0e875a2

**Comment by qibinc** [comment]
Hi @michaelpradel , Thanks a lot!!!
